language: node_js
node_js:
- stable
- '5.0'
- '4.0'
- '0.12'
- '0.11'
- '0.10'
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: kripod@protonmail.com
  api_key:
    secure: QHjr6dOmsPb/7DkVnyK7VhAdFDqi1c493f9rC13ihwlerdV2WXO6HyQscmF306C98pBhHSkUvdLC3lJYL+pBJhLtqQKZkO8bb2pqM+OhFMHUaCaJMGJXBT7/PQqW+6Wu6de9GMLq5wd9QcjtmLcIOwMEkQD4kYsli4RpoXElsaIaHabAvsVnpvg+2q/LBwr5WhNaxZOfnlI+K2iqupIvcq0cK7xvkR9Gjy6MuMW32+VgMWA9rcybpi9Trq2nhBXQYNbutn/w4yrxJmo1183gi85UEVOz9dpEt/F+YWX6B3HFPY2KdVYH+mSFAH3uJymOweGIT7RZ9IuAQ4Jjr8+EFYIqtFBpNt1o98nf1x6lTmdMVxvnqc4nT1LJDqztNnhzvCEgi4Nm/6FjXRh8++4Vo4TfxYJxQAnIOvBOV/fkhmPVASY/vHGcM6T9qoKpt3bvBoiQe2RE16zDvPb0pAGITTNwZXy9mdgKyfvybu/0iSL2sLoZauXJzy/s0QNjYRH4qWef4ml8giPnsGkcRTMhiwLBr1mxWojiWJ5rVeIYCrcluXunmXhUTA2FFde4VtcoanvQLZ8u7LEUxUpCvszzsS4sQ4RbSMGgaDWvK0AeoMAxc1hUgRd2/dGXxtAb8i4dvz7Orj+OGN4NNGP0dcM4h2j0Je2EuaXE9fJuRmDTRwQ=
  on:
    tags: true
    branch: master
    repo: kripod/hmac-rng.js
addons:
  code_climate:
    repo_token:
      secure: 08N8Dt8GHT2Cvh1dqpj8BO4ILuNCgu5GzcDpLVSvP5iRYIeXwi5ua9Tg/ES9KbBLzMVj4z5b2TlRqv7hrpMT4UunzKt9ACErVekcb6itu73iUSMPUHlJ4tyJT4rkS0GeV8Bk7GGw3RnujEl6OhMk1n10Dr+ybkNxxprv8bljYAsd93TjXHTLFDtTf5Nos6GuOsqt0rTHoPbAKs8o54vopVFj3RyFPl5jlE3PS6bMpmbPjhPBRyTnyvC7v1aSq1aRza1WdtpSCPgCk+f18pH7mdT4MwcqTiPCbvFDxVXctJEXc/P6m/5sq/+7vV8ijrXm4vTwhtYmyG5asSJeYD7h52IMCzqCLt9awNq00sLkpRVvqE9yYBFhe/4GAMaSOtvYGEMxvjv341G/lIXnwn7vYYaqKaqu0pcpxYOu9P68+B0Gr16eIR2iygA1qikNss4eO28oyPyaXc4O/rg0zG11+LjR9z/uF03KYfrk3c4c200pj1lhJtRkuDdO3+PZA8iqg5gKgTsldfToJ9vSOa71qS8h3XSdPtQpXwHPLxoD3m3+mDDSXJwQQ2b+Ip3g2TJ/uNZFy/daGClCn31mhMGq+rO+B+7BKD8kXme82FPqyV4WP/RfuwujZgnHMgNJcGrrBVMS+NR0RY/+3BHxgIFjkEwem11voCqtDQD5yRqTeAQ=
